#!/bin/bash
export PATH=$PATH:/usr/local/mysqlsh/bin

function assertAnyMysql()
{
    for node in $NODES
    do
        nc -q 1 $node 3306 </dev/null >/dev/null
        if [ $? -eq 0 ]
        then
            return
        fi
    done

    echo "No mysql nodes available"
    exit 1
}

function assertClusterExists()
{
    let n=0
    for node in $NODES
    do
        if [ $n -eq 0 ]; then
            nodes="\"$node\""
        else
            nodes="$nodes,\"$node\""
        fi
        n=$(expr $n + 1)
    done

    echo "nodes=$nodes"

    sed -e"s/NODES/$nodes/g" \
        -e"s/MYSQL_ROOT_USER/${MYSQL_ROOT_USER:-root}/g" \
        -e"s/MYSQL_ROOT_PASSWORD/${MYSQL_ROOT_PASSWORD}/g" \
        -e"s/MYSQL_GROUP_USER/${MYSQL_GROUP_USER:-innodb_cluster_admin}/g" \
        -e"s/MYSQL_GROUP_PASSWORD/${MYSQL_GROUP_PASSWORD}/g" \
        /usr/local/mysql/healthcheck.js > /usr/local/mysql/healthcheck.tmp.js

    if [ $? -ne 0 ]
    then
        echo "ERROR: sed failed"
        exit 1
    fi

    mysqlsh --file=/usr/local/mysql/healthcheck.tmp.js
    exit $?
}

##################
### MAIN #########
##################

NODES=$(getent hosts tasks.${MYSQL_SERVICE:-mysql-gr} | awk '{ print $1 }' | sort)
assertAnyMysql
assertClusterExists
