#!/bin/bash -eEu

# Check if Docker is installed already
if rpm -qa | grep docker > /dev/null
then
	echo 'Docker is already installed!'
	exit 1
fi
	 
# Register RHEL 7
sudo subscription-manager register --username gbertolini@csc.com --password 'M3sh@dmin!' --auto-attach

sudo yum-config-manager --disable rhel-7-fast-datapath-rpms

# Update registry
sudo yum update -y

# Install Git
sudo yum install -y git

# Retrieve Docker's Install script and execute it
curl -sSL https://get.docker.com/ | sh

# Allow smadmin to run Docker
sudo usermod -aG docker smadmin

# Install docker-compose
COMPOSE_VERSION=`git ls-remote https://github.com/docker/compose | grep refs/tags | grep -oP "[0-9]+\.[0-9]+\.[0-9]+$" | tail -n 1`

sudo sh -c "curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose"

sudo chmod +x /usr/local/bin/docker-compose

sudo sh -c "curl -L https://raw.githubusercontent.com/docker/compose/${COMPOSE_VERSION}/contrib/completion/bash/docker-compose > /etc/bash_completion.d/docker-compose"

# Unregister
sudo bash -c 'subscription-manager remove --all; subscription-manager unregister; subscription-manager clean'

# Start the docker daemon at boot
sudo chkconfig docker on


# Start Docker
sudo service docker start
